version: '2'

services:
    django:
        build:     
            context: .
            dockerfile: infrastructure/django/Dockerfile
        image: millidavids/django-in-docker:django
        env_file: .env
        volumes:
          - ./:/home/django
        ports:
          - "80:8000"
        depends_on:
          - db
    db: 
      image: postgres

